version: "3.7"

services:
  database:
    image: postgres
    container_name: loja-integrada-carrinho-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loja-integrada-carrinho
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: loja-integrada-carrinho-api
    ports:
      - 3000:3000
      - 9229:9229 # Debugger
    volumes:
      - .:/usr/app
      - exclude:/usr/app/node_modules/
    links:
      - database
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  pgdata:
    driver: local
  exclude:
    driver: local